export const strings = {
  to_do: "TO_DO",
  today: "Today",
  upcoming: "Upcoming",
  completed: "Completed",
  new_task: "New Task",
  add_title: "Add Title",
  add_your_task: "Add your task",
  dateTime: "Nov 1 2022 - 9:00 am",
  description: "Description",
  category: "Choose category",
  grocery: "Grocery",
  work: "Work",
  clearAll: "Clear all",
  university: "University",
  createNew: "Create New",
  doNotRepeat: "Do not repeat",
  save: "Save",
  customize: "Create New",
  doNotRepeat: "Do not repeat",
  home: "Home",
  tomorrow: "Tomorrow",
  upcoming: "Upcoming",
  add_task: "Create a new task",
  create_task: "Create task",
  add_description: "Add description",
  task_details: "Task details",
  no_task_completed: "No task completed",
  greetings: "Greetings",
  morning: "morning",
  evening: "evening",
  afternoon: "afternoon",
  Jan: "Jan",
  Feb: "Feb",
  Mar: "Mar",
  Apr: "Apr",
  May: "May",
  Jun: "Jun",
  Jul: "Jul",
  Aug: "Aug",
  Sep: "Sep",
  Oct: "Oct",
  Nov: "Nov",
  Dec: "Dec",
  ratingTitle: "Your opinion matters to us !",
  ratingSubTitle: "Give us a quick review and helps us to improve ?",
  rate: "Rate",
  not_now: "Not now",
  confimation_text1: "Are your sure?",
  confimation_text2: "You want to delete your task",
  delete: "Delete",
  cancel: "Cancel",
  edit: "Edit"
}