export const strings = {
  your_task: 'Your Task...',
  today: 'Today',
  upcoming: 'Upcoming',
  completed: 'Completed',
  new_task: 'New Task',
  add_title: 'Add Title',
  dateTime: 'Date and Time',
  description: 'Description',
  category: 'Choose category',
  grocery: 'Grocery',
  work: 'Work',
  university: 'University',
  createNew: 'Create New',
  doNotRepeat: 'Do not repeat',
  save: 'Save',
  customize: 'Create New',
  doNotRepeat: 'Do not repeat',
  home: 'Home',
  others: 'Others',
  Jan: "Jan",
  Feb: "Feb",
  Mar: "Mar",
  Apr: "Apr",
  May: "May",
  Jun: "Jun",
  Jul: "Jul",
  Aug: "Aug",
  Sep: "Sep",
  Oct: "Oct",
  Nov: "Nov",
  Dec: "Dec",
}