pipeline {
    agent any

    tools { nodejs 'node' }

    stages {
        stage('Build') {
            steps {
                bat 'yarn install'
            }
        }
        stage('Testing') {
            steps {
                bat 'yarn lint:fix'
                echo 'linting success'
                bat 'yarn test'
                echo 'Testing success'
            }
        }
        stage('APK Build') {
            steps {
                bat 'eas build --platform android --profile preview'
            }
        }
    }
}
