pipeline {
    agent {label 'linux'}

    stages {
        stage('Build') {
            steps {
                // echo 'Hello World'
                sh './scripts/hello.sh'
            }
        }
    }
}
