pipeline {
    agent any

    tools { nodejs 'node' }

    stages {
        stage('Build') {
            steps {
                bat 'yarn install'
                bat 'yarn test'
            }
        }
        // stage('Testing') {
        //     steps {
        //         bat 'yarn lint:fix'
        //         bat 'yarn test'
        //     }
        // }
        // stage('APK Build') {
        //     steps {
        //         bat 'eas build --platform android --profile preview'
        //     }
        // }
    }
}
