#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'pre-commit git hook'
echo '========  linting started  ========'
yarn lint-fix 
echo '========  linting succeed  ========'
echo '========  testing started  ========'
yarn test
echo '========  testing succeed  ========'
